zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"
kafka:
  build: .
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
   

springboot-hazelcast-mongodb:
  build: ./
  container_name: "micro-service"
  ports:
   - "8080:8080" 
  links:
   - zookeeper  
   - kafka
  

